# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "automerge"
      - "dependencies"
    reviewers:
      - "trevorgerhardt"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    # Increase the version requirements for package.json
    # only when required
    versioning-strategy: increase-if-necessary
