name: Build, Test, Deploy

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install

      - run: yarn build
      - run: yarn lint
      - run: yarn check-format
      - run: yarn jest
        env:
          CI: true

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: |
          export CYPRESS_baseURL=$(now deploy --no-clipboard --token $ZEIT_TOKEN)
          yarn cypress run --env $CYPRESS_GITHUB_ENV

        env:
          CYPRESS_GITHUB_ENV: ${{ secrets.CYPRESS_GITHUB_ENV }}
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
