name: Deploy to Zeit Now

on: [push, pull_request]

jobs:
  now:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo $PREVIEW_URL
        env:
          PREVIEW_URL: $(now deploy --no-clipboard --token ${{ secrets.ZEIT_TOKEN }}
